# Configuration file for the image classification application
#
# Date: July 2019
# Author: Lara Lloret Iglesias
# Email: lloret@ifca.unican.es
# Github: laramaktub
#
# References
# ----------
# https://pyyaml.org/wiki/PyYAMLDocumentation


#####################################################
# Options for general configuration
#####################################################

general:

  base_directory:
    value: "."
    type: "str"
    help: >
          Base directory for data and models. All the data that will be read and written will be done within this
          directory.
          If path is relative it will be appended to the package path.

  data_dir:
    value: "data/output"
    type: "str"
    help: >
          Base directory for images. If the path is relative, it will be appended to the package path.
